name: google_geocoding_api
description: This Package implement Google Geocoding API with default and reverse geosearch
version: 1.4.1
homepage: https://github.com/Dimolll/google_geocoding_api


environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  
dev_dependencies:
  lints: ^2.1.1